language: php
php:
- '5.6'
- '7'

services:
  - mysql

before_install:
  - pecl install swoole
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ci;'
  - mysql -e 'use ci;'
  - mysql -e 'CREATE TABLE `ci`.`hello` (`id` int(11) NOT NULL AUTO_INCREMENT,`content` varchar(255) NOT NULL,`user` varchar(255) NOT NULL,`created` datetime NOT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;'

install: composer install -vvv

script: vendor/bin/phpunit
