language: php
php:
- '5.6'
- '7'

services:
  - mysql

before_install:
  - pecl install swoole
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ci;'

install: composer install -vvv

script: vendor/bin/phpunit
