author:
    - janhaung
    - wait

database:
    driver: mysql
    default_connection: read
    write:
        host: localhost
        port: 3306
        user: root
        pwd: 123456
        charset: utf8
        dbname: test
    read:
        host: localhost
        port: 3306
        user: root
        pwd: 123456
        charset: utf8
        dbname: sf_blog
        prefix: sf_

cache:
    driver: redis
    default_connection: redis1
    redis1:
        host: localhost
        port: 3306
        user: root
        pwd: 123456
        charset: utf8
        dbname: test
