# dev evn config

database:
    default_connection: read
    write:
        database_type: mysql
        database_host: localhost
        database_port: 3306
        database_user: root
        database_pwd: 123456
        database_charset: utf8
        database_name: test
        database_prefix:
    read:
        database_type: mysql
        database_host: localhost
        database_port: 3306
        database_user: root
        database_pwd: 123456
        database_charset: utf8
        database_name: test
        database_prefix:

# Template engine and templates path setting
# If you should add new template path.
# examples:
# create one new path
# paths:
#     - new path
template:
    engine: twig
    paths: [ %root_path%/resources, %root_path%/../src ]
    cache: %root_path%/cache/

error_page:
    500: error/error.html.twig

# The bundles prefix setting.
routing:
    config: %root_path%/config/routing.yml

#这个是日志配置，没什么事，就别作死了。
logger:
    type: monolog
    path: %root_path%/logs/%Ymd%

