# dev evn config

database:
    default_connection: read
    write:
        database_type: mysql
        database_host: localhost
        database_port: 3306
        database_user: root
        database_pwd: 123456
        database_charset: utf8
        database_name: test
        database_prefix: sf_
    read:
        database_type: mysql
        database_host: localhost
        database_port: 3306
        database_user: root
        database_pwd: 123456
        database_charset: utf8
        database_name: test
        database_prefix: sf_

template:
    engine: twig
    paths: [ %root_path%/resources, %root_path%/../src ]

routing:
    config: %root_path%/config/routing.yml

logger:
    type: monolog
    path: %root_path%/logs/%date%
    rule: %date%.log
    auto_create: true
