# Dobee php simple framework global config.

database:
    default_connection: read
    write:
        database_type: mysql
        database_host: localhost
        database_port: 3306
        database_user: root
        database_pwd: 123456
        database_charset: utf8
        database_name: sf_blog
        database_prefix: sf_
    read:
        database_type: mysql
        database_host: localhost
        database_port: 3306
        database_user: root
        database_pwd: 123456
        database_charset: utf8
        database_name: sf_blog
        database_prefix: sf_

#下面的，没什么事就不要乱动。
template:
    engine: twig
    paths:
        - %root.path%/resources
        - %root.path%/src
    options:
        cache: %root.path%/cache/%env%

errors:
    page:
        #500: views/errors/500.html.twig

#这个是日志配置，没什么事，就别作死了。
logger:
    path: %root.path%/logs/%date%/dobee.log


