import:
#    - { resource:  }

drivers:
    database:
        default_connection: read
        write:
            db_driver: mysql
            db_host: localhost
            db_port: 3306
            db_user: root
            db_pwd: 123456
            db_charset: utf8
            db_name: sf_blog
            db_prefix: sf_
        read:
            db_driver: mysql
            db_host: localhost
            db_port: 3306
            db_user: root
            db_pwd: 123456
            db_charset: utf8
            db_name: sf_blog
            db_prefix: sf_
        read2:
            db_driver: mysql
            db_host: localhost
            db_port: 3306
            db_user: root
            db_pwd: 123456
            db_charset: utf8
            db_name: sf_blog
            db_prefix: sf_

    cache:
        default_connection: redis1
        redis1:
            cache_driver: redis
            cache_host: localhost
            cache_port: 3306
            cache_user: root
            cache_pwd: 123456
            cache_charset: utf8
            cache_dbname: test

template:
    engine: twig