groups:
    admin: /admin

_welcome:
    path:       /
    callback:   DemoBundle\Controllers\DemoController@demo
    formats:    [ json, php ]
    defaults:
    requirements: { name: \w+ }
    methods:    [ANY]

demo:
    type: annotation
    resource: DemoBundle\DemoBundle

_resource:
    type: annotation
    resource: Demo\DemoBundle\DemoBundle