#_welcome:
#    path:       /
#    callback:   DemoBundle\Controllers\DemoController@demo
#    formats:    [ json, php ]
#    defaults:
#    requirements: { name: \w+ }
#    methods:    [ANY]

_welcome:
    type: annotation
    resource: Welcome\Welcome